hash-format = "sha256"

[[files]]
file = ".github/workflows/version-and-release.yml"
hash = "d9c3e10e96363e7814c0986f91935333d403956a36e6feef53d199805af66324"

[[files]]
file = "LICENSE"
hash = "c58fb495769c8e6f4c77d05a2d86e529ec4c599ad318c2169a23f805c6f8e2d9"

[[files]]
file = "README.md"
hash = "925916059b279a002690f71da5f5fbedb5db6b74bbee1f3e524226692975be9a"

[[files]]
file = "config/authme.json5"
hash = "d6c3d2eaebe5056d236b3e6d6f7311c726d3e9a59f26e4b2b3ca3ed4abc12cac"

[[files]]
file = "config/axesareweapons.json5"
hash = "f6162aa89e46306ed963af9f3f652681e3d165536808d10220ce02b034c5ef41"

[[files]]
file = "config/defaultoptions/extra/config/inventoryprofilesnext/inventoryprofiles.json"
hash = "65eb7e1d00aa7dad06af151fd4c1b4c8a67b012dab6c4c94a337325465535fa2"

[[files]]
file = "config/defaultoptions/extra/config/waila/waila.json"
hash = "330aab621136eaa47f46bee2b17187122e8515a52226ffb6d9cb7345840b2f36"

[[files]]
file = "config/defaultoptions/extra/config/waila/waila_plugins.json"
hash = "ca51ffde7334f601e6ed95ee89d112b45d2714bb0e075e131db7e86c288b7193"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "c1c54862c9066f328f5cdc178124fe798fc7df521e9e01ef5f7eba10c0932467"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "8b97b37d6c985054846e330f4c7e35e2db8c0f4d79f1019a86646b964acb999c"

[[files]]
file = "config/fallingleaves.json"
hash = "6c5be5c1f0093db01d04f03c6bcdc208762b83279604ffaefafb10890703c96d"

[[files]]
file = "config/fallingtree.json"
hash = "a3d0e5277d3ad0a6bfb71a84a50ca30490a537159f7efce5af46645648bb582d"

[[files]]
file = "config/immersive_portals_fabric.json"
hash = "4e79df157dd0d33c92eaadd5ad63bfddab19fd3d0e8afe44cf36621781313ee3"

[[files]]
file = "config/immersive_weathering.json5"
hash = "545c95f7c1dfa33b055f0c1abc34236937da2587fad4158578a96898c8b4d840"

[[files]]
file = "config/modmenu.json"
hash = "a4d3c29fe1f5207dfe54380105b54fd9cce5f82971e3dc888234aed6c41b78da"

[[files]]
file = "config/notenoughanimations.json"
hash = "5cdc679803fc168fb95bfad72b51ab23defc39d14b4c240b47ebbd426a3051a0"

[[files]]
file = "config/pettable.json"
hash = "108c339414ecc5a495902d798c9741453c6041e522f16aeac3cf29a4bcbd2560"

[[files]]
file = "config/realisticsleep.json"
hash = "d177e85570cb37a6e4fa65d797c2cb98b14f177cbfaf9868e4c2e1c51365a6d7"

[[files]]
file = "config/roughlyenoughitems/changelog.txt"
hash = "8d3828692497be68d54e98820db28df65ef79b28f16ec4ebeef0e0916588dd8e"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "4691399df2a7e227237a30a319eb93b49ec154e4541e1eaa8435ebfa2bc70c14"

[[files]]
file = "config/shulkerboxtooltip.json5"
hash = "c755fe54700f74f04bc4811aa976578da14e86ed37b82795a91466b40b0eec45"

[[files]]
file = "config/simple-rpc.toml"
hash = "f16161cb075c1fdf1a8aab25fbcd959d1740e5940bd8748872bda4d7ece46517"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "f8fa4170bd729e1211e3f611283a4c8caeecf913c6a31d238688ca233e0fca8f"
metafile = true

[[files]]
file = "mods/adorn.pw.toml"
hash = "4feaa4ce2ae7f59767eff008af133360b29a7ff154207703a88b674d8160291f"
metafile = true

[[files]]
file = "mods/advancements-debug.pw.toml"
hash = "ee594d77a6bf804bece719158860532f059ecb4181d8740d16e73e0f19d8415e"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "f326f406c7d2d9a9630614877f7c8e208128407bfdfd5882a897dee7103b16b6"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "544bc995469ff0df6f5bee4422157ee3b5afc912ee69e1acca18aed9eee45dea"
metafile = true

[[files]]
file = "mods/architects-palette-fabric.pw.toml"
hash = "089fdd874610a3d4fc20820f502aee8ede9c0c96ffeaa51ee9d5a385588fcc52"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "3b159279fb38b296896f52f938286f4606bc7699796a1491a27f89ded32616ef"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "becf86edfc92ca0ae0a9584ace31dcaf2042833ddf131fe011f811593e4e89ed"
metafile = true

[[files]]
file = "mods/axes-are-weapons.pw.toml"
hash = "17286bf8c9bcbb1aae16dca55cd42d139bb034e11bca5a5284808284330b0d98"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "d8fe226cd050b8c94fcb98819b2646a74863ad8d52fc22db37c29fe66e53996d"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
hash = "2cb38bb1677800e5ca67c6e2055dd677a4cc90b1f86778ad266a2e874080d8ee"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "f3bd27c5634ac6176e3dd6c61645de4110700321b9505bafce051bce509fa8de"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "3923281577b1d02baa68e8bde42106900e85604f17ce7d0d3ba2382de7a809b2"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "a9d766e948727e1229bc4dc33ab57ed868b4d5c7b5bc643dc1ad22de094063c8"
metafile = true

[[files]]
file = "mods/brb.pw.toml"
hash = "f4b6d802ca101f8f33f320b06295f8ed2337b9e9ebda82c9cdf6a9d8982383e7"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "95cc8d9a9619ccde6bdb1f2b1b122a459635b3a00f315c7104ca1d9b8692c1c4"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "e62bcbd10d62cb220966fdafe865b6c476cb9fea1acca6772db817ca549ed519"
metafile = true

[[files]]
file = "mods/cloth-api.pw.toml"
hash = "d9eaa84685824313f68af59cc78ba4bb572252bee35d4c7084c682559a3e1e7a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "893ccafbecdce36b1d44e62d9e9da043ad869c6e3b32f58e00769e7b8083e7b0"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "15d63e38b75a8c1263f5b1ead4b70e885f2984a8a3140a06d47286ca35a94f06"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "05cc94e228b268f5d462eb38daa482aad30fa17bb3f0f74397a20838d157bd95"
metafile = true

[[files]]
file = "mods/connecteddoors.pw.toml"
hash = "c191b749f600fb2b9ac5ea29b5994ff698c51d5f84fe93961d4699cbfe89a615"
metafile = true

[[files]]
file = "mods/connectible_chains.pw.toml"
hash = "c72b99357e64c2a9d3c49176b207944eb6d6c42df5ee375d63c1ed800a988390"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "01efd2f7388304c96bc74c8f074b22a3b6f162465c61b82915b546c4f6f47615"
metafile = true

[[files]]
file = "mods/cosmetic-armor.pw.toml"
hash = "47a6fb154e259ede68a3c3f36b455cfa089b93f1af662ef567cf3598dc5301ce"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "ec083ae7dc4dd9625b1ce84aa163f6d9314298b83df2ec1ffcaec522d80b3d75"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "1993e269ab8d9532b524050d33e0fa691c43aa5d3ccff06f2a478aaeb98a18d8"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
hash = "43982514d3d3a8309732c85708d489bfb67986723f2117fca4a7b5c2093ca6fe"
metafile = true

[[files]]
file = "mods/default-options-fabric.pw.toml"
hash = "e42d89621edc41efb4fc38b7023a677f188cf8593e16cc2eb5cae51daf098cdf"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "03ab8fccf4b56d8275a48a78cc141e20d72e49889ae05f37d37f87c0f52e7636"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "3e7ba23bc1d585377e03937f3b5a8ab247cae4697300039db557c3dab788cb61"
metafile = true

[[files]]
file = "mods/editsign.pw.toml"
hash = "0c5b24ff78ffbb84a8dec083eeee84973b0985a3db6a93d868e391101eb7fe7a"
metafile = true

[[files]]
file = "mods/elytra-slot-fabric.pw.toml"
hash = "5aa21034de092be162a762dc5cb69b66f8bfec90d4d1cb0e544c094066021ca3"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
hash = "f76a74f2e9a6a9940de3dc3d6f7eac7478e233b66bef550d77ed003ed7423d1f"
metafile = true

[[files]]
file = "mods/expanded-armor-enchanting.pw.toml"
hash = "ea89cd959d70ad5d80f3b43ae7b2402972401b58524b04852edc494fbefcb586"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4c99c46630a021c6517c901dd42d1867271f5f30dc4b7b575280a205685b892a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "65629e215ca8bd277eebbd925a927ad6001d347edb4839c32674c7bb5bb534c1"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
hash = "835f909dbb4eebbed74617500990e3486382c7d83fd0d031a728dd7152423e05"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "69d366ce8b45de07448a10e1141dd9ac02d68d1afd1da6c1a2a5ed586ccd3078"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "eff7fef8125fc79df6c2ffbc15c25ca846dd3f0e760cb6fae774ae077b66e437"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "c2e610ae93f0585aa37107d4289a8ce54b4cb0a55250ee0e77bdd8eaf7896a4a"
metafile = true

[[files]]
file = "mods/feature-nbt-deadlock-be-gone.pw.toml"
hash = "9c2283edd0c654e6176f10205fac20de46af3c0fe0f73910f9a51157ae2a1dac"
metafile = true

[[files]]
file = "mods/frame-api.pw.toml"
hash = "91b4a0b8001afd34680aec03757b5ef5227927b4cc28ce9d29a480b32184ce17"
metafile = true

[[files]]
file = "mods/gimme-bundles.pw.toml"
hash = "185344af1d4276051bb8dcf2e4952960e0681bf39d678ddb1ccfc35b03b86464"
metafile = true

[[files]]
file = "mods/half-doors.pw.toml"
hash = "aa73369ff94a6d42f3390f3c7149866e46fc50b944a0a2ec5df09453265c1f74"
metafile = true

[[files]]
file = "mods/immersive-weathering.pw.toml"
hash = "010d174143b09fb849dee44cada9f82758beb62acfe8ba9420d3fcd3aee5c3e2"
metafile = true

[[files]]
file = "mods/immersiveportals.pw.toml"
hash = "90dc8b5f4c8db6692c70912fb76f2944df58d1fe3790676051d040e5907df6c4"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "eec174f63af5bae8eba9a4357bd2bfa7432afb1e9faa21ae8839aacccc36cf32"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "9c908319196e0e2a75d9606aa01baecf02d4e492e5590df5b2629aacec7cfb1a"
metafile = true

[[files]]
file = "mods/inventory-tabs-updated.pw.toml"
hash = "4260894fd18d9e593e8364a0ac3aab1ac7ba6b654010a928f05f12f1e1a83006"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
hash = "e758133dad47a630e32aa03aad1acc85dd6e96c1f6569d8b7ae6e7d272cb9318"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "229b09f29d225f71b95737207af93f77e1fde9a19aa8fafc22bc9dc652ed1d13"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d1bfbb6ca8b538cfa37e439ff8d3ffc965d20054d67d7d727f594df1113d79d0"
metafile = true

[[files]]
file = "mods/map-atlases.pw.toml"
hash = "c60a107bd8f0eeec2e03a3fa6839666bbebe2261d4605b408be1645a57e659f8"
metafile = true

[[files]]
file = "mods/mo-structures.pw.toml"
hash = "0bdb1f19e3f9086941ea2b69672e1a675b39a6b0bdda9da375ca22f3d86f16c8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "787673fa16e88c32e4b9ada118b7d01ee67f9ea4b8bd2c582cd55d9919b601a4"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "f32979a49a41c89459db197bac02e4f9eec07300d52c78517a327f9f0d9d73a7"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "b92ef307ec9cbafb8502d768382dfb4cb3252f1d680628518c4ad22a03962b9f"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "dc8b200052c6b0729ecd6f5f69365483875c4de1c14a50ca353e958bc8427caa"
metafile = true

[[files]]
file = "mods/pettable.pw.toml"
hash = "9b42007916839b593d0e78757776a0eab9d56355d8f1d964cc851fb5fe62e229"
metafile = true

[[files]]
file = "mods/phosphor.pw.toml"
hash = "b2ad206bb06c3fcf4a7626ebbcdaf7439934ac42aa14a39ad1e30c8bfe6de126"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
hash = "5c29dbcf22275238ecd6250c20e7cfd4eef27b3efa79db448045ff9512143a07"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "b66864461ab50ed6edcd149cb31ddb1ae278a5c8cea57ae95353b0350cae61c4"
metafile = true

[[files]]
file = "mods/realisticsleep.pw.toml"
hash = "7b16ef48b0a5b0fa62092c998d0eb90de34f868f6cba5db46f2f50ba526627ce"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "ea6853435e218bd8ad600579ecdb93075d8775ea083f60defd26bb5c4d1a9266"
metafile = true

[[files]]
file = "mods/right-click-harvest.pw.toml"
hash = "ac40807815067e822aed363a76704930f7cc02f940868b27089d8068c89c238c"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "e1c929522a79ebca325eac84166adea5374689c533813a9838cd7325a6e49931"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "67ac7ba93649c60e127b8b0c90889aed07837763b2250cfc9face0545e6888fc"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "d82933da248c33056918940d533d950eeef45a9e91340714e264b78293e14d8e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "de1442e146d6c3ca804acdae8dc855c11601c55321835d457d53ed939a4cda67"
metafile = true

[[files]]
file = "mods/statuseffecttimer.pw.toml"
hash = "ed6bf626eaf7b66cd33fcb7058ec3feaae079a84c4540d07f1a8f1c6a808d4e4"
metafile = true

[[files]]
file = "mods/tax-free-levels.pw.toml"
hash = "a34b891acdc746edb3e89e8ad7bb930ef2c93be60628b6e4219dbe9b89cda8b9"
metafile = true

[[files]]
file = "mods/terrablender-fabric.pw.toml"
hash = "7864b53998be095c3eb099839980c5129240098905ae53942acac1d8b7e3bad5"
metafile = true

[[files]]
file = "mods/traverse.pw.toml"
hash = "153bf84b3deb5ec1f13ae25b0130db4a5aa7fafdd8061d772d24dcdd85e8e631"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "1d5aa98aff5c7f9d5c0b3736a624c8f28f9aa5164aa658c409be19449feb4c45"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "b1778c8b8e1ad8b197e2196656db06ed757decc6c3a1b657a257a586ff8eafe4"
metafile = true

[[files]]
file = "mods/universal_ores.pw.toml"
hash = "3efc7a8c12f81ca90742680a544252cf23131275161729bbdffd8a1e3d188865"
metafile = true

[[files]]
file = "mods/variant-crafting-tables-fabric.pw.toml"
hash = "543e2336660f18352ac3e50d2958f5b4dbf6c09689948f1d2d7f7d3e6a19ec4d"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "a7afab7e7e9e2302fe27b3cb2fddf42ebb8aadf9203de39240726dcb3e667cc6"
metafile = true

[[files]]
file = "mods/where-is-it.pw.toml"
hash = "d9ad958ea7f973474667ee8548b7536c34a3ed7b5cbc8dec0c53c9e0d68d7e77"
metafile = true

[[files]]
file = "mods/wthit-plugins.pw.toml"
hash = "d1cde539d883aa503e4f8402ba11dd78e4ee4664e4f87badd1f8003c8adae419"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "74bed3f89d10be79e01a8a381e54dfbf57af973907dd56a7cbb3fe7d1e1682bf"
metafile = true
